### ISSUE TITLE
"configure: error: Could not link against  !"

### ISSUE THREAD

**Issue by pbiggar** [pbiggar/phc#141]
```
I'm really not sure what info you need me to supply, but I had a problem configuring
the svn-trunk of phc on Ubuntu 10.10. I installed all of the dependencies except libxerces-27,
which was not found. I installed libxerces-c2-dev instead.

Here is the last bit of the ./configure output. Please let me know if this is insufficient
and I will send more information.

checking for gengetopt... config/phc_missing gengetopt
checking for gperf... config/phc_missing gperf
checking for flex... config/phc_missing flex
checking for bison... config/phc_missing bison
checking for valgrind... no
checking for dot... /usr/bin/dot
checking for gc... /usr/bin/gc
checking for maketea... config/phc_missing maketea
checking for php... /usr/local/bin/php
checking for zend_eval_string in -lphp5... no
checking for sapi/embed/php_embed.h... yes
checking whether compiler supports covariant returns... yes
checking for /usr/lib/libCrun.so.1... no
checking for boostlib >= 1.35.0... yes
checking whether the Boost::Regex library is available... yes
configure: error: Could not link against  !
```

Original issue reported on code.google.com by `shabbyrobe` on 2010-11-13 10:13:46

**Comment by purnimam** [comment]
Hi, I am getting this configure error "configure: error: Could not link against  !" when trying to install nox13oflib on ubuntu 14.10.   I have already installed libboost-all-dev and every dependencies. Kindly help.

**Comment by renaldi1982** [comment]
I've had the same error and for some reason using ./configure --with-boost-regex=boost_regex fixed it for me.

**Comment by walid32** [comment]
purniman how did u solve the error. Could not link against

**Comment by purnimam** [comment]
I couldn’t solve it. I had to go back to ubuntu 12.04.

On Sat, Dec 26, 2015 at 4:23 AM, walid32 <notifications@github.com> wrote:

> purniman how did u solve the error. Could not link against
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiggar/phc/issues/141#issuecomment-167261178>.
>



-- 
*Regards,*


*Purnima MuralimohanNational University of Singapore*
