### ISSUE TITLE
configure: error: Could not link against boost_regex !

### ISSUE THREAD

**Issue by pbiggar** [pbiggar/phc#163]
```
What steps will reproduce the problem?
1.I cannot install phc-0.3.0.1 on ubuntu 12.04  LTS (32 Bit)
2.
3.

What is the expected output? What do you see instead?
checking for boostlib >= 1.35.0... yes
checking whether the Boost::Regex library is available... yes
checking for exit in -lboost_regex-mt... no
checking for exit in -lboost_regex-mt... (cached) no
checking for exit in -lboost_regex... no
checking for exit in -lboost_regex... (cached) no
checking for exit in -lboost_regex... (cached) no
checking for exit in -lboost_regex... (cached) no
configure: error: Could not link against boost_regex !



What version of the product are you using? On what operating system?
php-5.5.7/
phc-0.3.0.1

Please provide any additional information below.
Please look at the attachment.

Please help i cannot solve the problem since many days.

```

Original issue reported on code.google.com by `methodxjp@yahoo.fr` on 2013-12-16 23:09:19
<hr>
 * *Attachment: [config.log](https://storage.googleapis.com/google-code-attachments/phc/issue-154/comment-0/config.log)*

**Comment by miches** [comment]
I cannot get this to compile either. I use Ubuntu 14.04.2 LTS in both 32-bit and 64-bit variants, and on both systems, I get the exact same error as above after I compiled php with SAPI support to /opt. I tried both the last tarball I could find (0.3.0.1) and the current github repository, with the same result. 

If I just type "./configure", the script fails with

```
checking for boostlib >= 1.35.0... yes
checking whether the Boost::Regex library is available... yes
configure: error: Could not find a version of the Boost::Regex library!
```

which is not very helpful as he claims to both have found and missed out on the boost-regex libary (which of course is installed)

If I type "./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu/" (which is the path to the boost libs) instead, I get: 

```
configure: WARNING:
*******************************************************************************
* It seems the PHP embed SAPI has not been installed.                         *
*                                                                             *
* You will be able to compile and run phc, but you will not be able to        *
* compile PHP scripts with phc.                                               *
*                                                                             *
* To install the PHP embed SAPI, follow the PHP installation instructions,    *
* but make sure to pass the --enable-embed option to the PHP configure        *
* script.                                                                     *
*******************************************************************************
```

which seems reasonable as the script is detecting the ubuntu-installed, non-SAPI version of php in the default path. So, I try "./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu/ --with-php=/opt" (php is installed under /opt, the SAPI-enabled php binary is located at /opt/bin/php). This provides me with the above error:

```
checking for boostlib >= 1.35.0... yes
checking whether the Boost::Regex library is available... yes
checking for exit in -lboost_regex... no
checking for exit in -lboost_regex... (cached) no
checking for exit in -lboost_regex... (cached) no
configure: error: Could not link against boost_regex !
```

and nothing left to try. 

What am I doing wrong? Doesn't this work anymore? I need a way to build executables from PHP scripts, and hiphop doesn't seem to do that anymore, either. :-(

**Comment by miches** [comment]
Not a single reply in more than two weeks - this project is dead, right? :-(

**Comment by pbiggar** [comment]
Yeah, unfortunately :(

**Comment by neo4u** [comment]
Could you please let me know as to what is the latest version of PHP that works well with the latest version of PHC?

**Comment by pbiggar** [comment]
PHP 5.2 definitely worked, though I think I recall PHP 5.3 working as well, and maybe PHP 5.4.

**Comment by dukebarman** [comment]
I've a same problem. Maybe create a docker image for phc?

**Comment by pbiggar** [comment]
Fixed on master.
