### ISSUE TITLE
Remove phpcompiler.org

### ISSUE THREAD

**Issue by kenorb** [pbiggar/phc#170]
Please remove links to phpcompiler.org (GitHub description and README) as it points to the spam website.

**Comment by pbiggar** [comment]
Good idea, thanks! Can you make a PR?

**Comment by pfalcon** [comment]
Why not make https://github.com/pbiggar/phpcompiler.org deploy to phc.github.io and link to it instead?

**Comment by thomwiggers** [comment]
> Good idea, thanks! Can you make a PR?

the github description link has to be changed by the owner of the repository

**Comment by kenorb** [comment]
Fixed in b3f21b6f75c95b30463cc0247a7e618aae818963.

**Comment by pbiggar** [comment]
And I remove the link in the github description as well.
